---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - monitoring.motnitoring-test.com
  resources:
  - monitoringtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.motnitoring-test.com
  resources:
  - monitoringtests/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.motnitoring-test.com
  resources:
  - monitoringtests/status
  verbs:
  - get
  - patch
  - update
